#!/usr/bin/env bash

set -e

AVER="\033[38;5;185m"
DENY="\033[38;5;9m"
CLR="\033[0m"

asdf_script='https://github.com/briskconfig/get-asdf/raw/refs/heads/release/asdf.sh'
grab_latest='https://github.com/BriskBear/profile.d/raw/refs/heads/release/grab_latest.sh'
XP=$HOME/.local/etc/profile.d

[[ `git` ]] || ( echo -e "${ERR}asdf requires git, please install git and try again${CLR}" ; exit 1 )

# Prefer curl else find wget
if [[ `curl 2>/dev/null` == 127 ]]
then [[ `wget 2>/dev/null` == 127 ]]                                                   \
  && ( echo -e "${DENY}Error: Install 'curl' or 'wget' and try again.${CLR}" ; exit 2 ) \
  || web='wget -S'
else web='curl -#L'
fi

# Create user's .local directories for standard profile
mkdir -p ~/.local/{bin,etc/profile.d,share/asdf}

`${web} ${grab_latest} > $XP/grab_latest.sh`
. $XP/grab_latest.sh
printf "\033[1A\033[0G\033[0K"

# Download and Extract asdf binary to the path
pushd $HOME/.local/bin &>/dev/null
  grab-latest asdf-vm/asdf
  printf "\033[1A\033[0G\033[0K"
  ${web} $asdf_script > $XP/asdf.sh
  printf "\033[1A\033[0G\033[0K"
popd &>/dev/null

echo -e "${AVER}asdf-vm installed! use \`. ~/.bashrc\` to load${CLR}"
